"""added script_name field to algorithm table

Revision ID: e886148ac8b0
Revises: 9050b5f26e14
Create Date: 2020-03-07 09:16:28.917311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e886148ac8b0'
down_revision = '9050b5f26e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('script_name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algorithms', 'script_name')
    # ### end Alembic commands ###
